version: "3.9"

services:
  anythingllm:
    image: mintplexlabs/anythingllm
    container_name: anythingllm
    ports:
      - "3001:3001"
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./data:/app/server/storage
      - ./.env:/app/server/.env
    environment:
      STORAGE_DIR: "/app/server/storage"
    restart: unless-stopped
    
  gateway:
    image: docker/mcp-gateway
    command:
      - --servers=duckduckgo
      - --transport=streamable     # or: --transport=sse
      - --port=8811
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8811:8811"
